### ISSUE TITLE
Multilanguage Image show G4 problem

### ISSUE THREAD

**Issue by pfrankowski** [GavickPro/Image-Show#52]
When somebody uses SEF and different languages - Multilanguage enabled -- module have problem with showing images :

www.domain.com  --- there module will show image
www.domain.com/es  - no images in module
www.domain.com/en  - no images

**Comment by JialuZhang** [comment]
@pfrankowski @dziudek 

In your posted configuration,
```
RewriteEngine Off
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
